filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/dockerlogs/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

processors:
  - add_host_metadata: ~