global:
  scrape_interval:     3s
  external_labels:
      monitor: 'twitter-app'
rule_files:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'twitter-app'
    static_configs:
      - targets: ['frontend:9200']